name: Feature Branch CI Pipeline

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened]

jobs:
  quality-check:
    if: startsWith(github.head_ref, 'feature/ticket-')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Simple Quality Check
        run: |
          echo "✅ Проверка качества кода прошла успешно!"
          exit 0

      - name: Send Telegram Notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *GITHUB_DEVOPS_BOT*
            🚀 *Новый выпуск изменений*
            *Проект:* ${{ github.event.repository.name }}
            *Ветка:* `${{ github.head_ref }}`
